(()=>{
const HISTORY_KEY='fc_recent_places_v46';
const SNAPSHOT_KEY='fc_last_snapshot_v46';
const $=s=>document.querySelector(s);
function getHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return []}}
function saveHistory(item){const list=[item,...getHistory().filter(x=>x.name!==item.name)].slice(0,8);localStorage.setItem(HISTORY_KEY,JSON.stringify(list));renderHistory()}
function renderHistory(){const host=$('#placesSaved');if(!host)return;const list=getHistory();if(!list.length){host.innerHTML='<div class="historyEmpty">Sin localidades recientes.</div>';return}host.innerHTML='<div class="historyList"><h3>Consultas recientes</h3>'+list.map((x,i)=>`<div class="historyItem"><div><b>${x.name}</b><small>${new Date(x.time).toLocaleString('es-ES')}</small></div><button data-history="${i}">Abrir</button></div>`).join('')+'</div>'}
function saveSnapshot(){try{const data={time:new Date().toISOString(),html:$('#localReport')?.innerHTML||'',results:$('#placeResults')?.innerHTML||''};localStorage.setItem(SNAPSHOT_KEY,JSON.stringify(data))}catch{}}
function restoreSnapshot(){if(navigator.onLine)return;try{const s=JSON.parse(localStorage.getItem(SNAPSHOT_KEY));if(!s)return;const box=document.createElement('div');box.className='offlineSnapshot on';box.textContent='Sin conexión. Mostrando la última información guardada: '+new Date(s.time).toLocaleString('es-ES');$('#localReport')?.prepend(box);$('#localReport').insertAdjacentHTML('beforeend',s.html)}catch{}}
async function loadDanger(){const link=$('#aemetDangerLink');if(!link)return;const lat=40.4167,lon=-3.7033;try{const r=await fetch(`/api/fire-danger?lat=${lat}&lon=${lon}`);const d=await r.json();const card=$('#preventionPanel');if(!card)return;const status=d.configured?'Integración automática disponible':'Visor oficial disponible';card.insertAdjacentHTML('beforeend',`<div class="preventionStatus"><div><small>Fuente</small><strong>${d.source}</strong></div><div><small>Estado</small><strong>${status}</strong></div></div><div class="preventionDisclaimer">El peligro meteorológico no significa que exista un incendio. Es una condición preventiva.</div>`)}catch{}}
async function share(){const text='Fuego Centro: consulta de situación de incendios forestales. '+location.href;if(navigator.share){await navigator.share({title:'Fuego Centro',text,url:location.href})}else{await navigator.clipboard.writeText(text);const b=$('#sharePanel');b.insertAdjacentHTML('beforeend','<div class="shareFeedback">Enlace copiado.</div>')}}
function bind(){renderHistory();loadDanger();restoreSnapshot();$('#shareReportBtn')?.addEventListener('click',share);$('#localReport')&&new MutationObserver(()=>{saveSnapshot();const text=$('#localReport').textContent||'';const m=text.match(/(?:Informe de|Situación de)\s+([^\n]+)/i);if(m)saveHistory({name:m[1].trim(),time:Date.now()})}).observe($('#localReport'),{subtree:true,childList:true});document.addEventListener('click',e=>{const b=e.target.closest('[data-history]');if(!b)return;const item=getHistory()[Number(b.dataset.history)];if(item){$('#placeQuery').value=item.name;$('#placeSearchForm')?.requestSubmit()}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
